# Generated by Django 3.2.7 on 2021-09-12 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Phisher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
